version: "2.1"
services:
  filebeat:
    image: elastic/filebeat:7.10.1
    container_name: filebeat
    hostname: filebeat
    privileged: true
    command: /usr/share/filebeat/filebeat -c /usr/share/filebeat/conf/filebeat-logstash.yml -e 
    volumes:
      - ./conf/:/usr/share/filebeat/conf
      - ./data:/usr/share/filebeat/data
    networks:
      - elk_es-network
# 网络直接使用的是搭建elk构建的网络，目的为在同一网络下
networks:
 elk_es-network:
  external: true