filebeat.inputs:
- type: log
  enabled: true
  paths:
   - /usr/share/filebeat/data/logstash.log

setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
output.logstash:
  hosts: ["logstash:5044"]
# output.console:
#   pretty: true