filebeat.inputs:
- type: log
  enabled: true
  paths:
   - /usr/share/filebeat/data/*.log

setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
output.elasticsearch:
  hosts: ["node1:9200", "node2:9201", "node3:9202"]
