version: '3.3'
services: 
  oracle: 
    image: registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g
    container_name: oracle
    ports: 
      - "1521:1521"
    environment:
      ORACLE_HOME: /home/oracle/app/oracle/product/11.2.0/dbhome_2
      ORACLE_SID: helowin
      PATH: $ORACLE_HOME/bin:$PATH
    command: ln -s $ORACLE_HOME/bin/sqlplus /usr/bin
