version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    hostname: prometheus
    volumes:
      - /root/docker/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 19090:9090
    networks:
      - ck-net

  grafana:
    image: grafana/grafana:9.0.1
    container_name: grafana
    hostname: grafana
    ports:
      - 13000:3000
    networks:
      - ck-net

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/containers:/var/lib/docker:ro
    networks:
      - ck-net

networks:
  ck-net:
    external: true

# Grafana Dashboard ID
# Clickhouse:14192, Docker:193, Kafka:12460, Node Exporter:8919
