version: "3"
services: 
  flume:
    image: wxk749/flume:1.10.0
    hostname: flume
    container_name: flume
    volumes:
      - ./kafka.conf:/opt/flume-config/flume.conf
      - ./data:/tmp/data
    environment:
      - FLUME_AGENT_NAME=docker
    networks:
      - ck-net

networks:
  ck-net:
    external: true
