version: "2.1"
services:
  node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: node1
    expose:
      - "9001"
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./node1/node1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      es-network:
        ipv4_address: 172.21.0.10
  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: node2
    expose:
      - "9002"
    ports: 
      - "9201:9201"
      - "9301:9301"
    volumes:
      - ./node2/node2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      es-network:
        ipv4_address: 172.21.0.11
  node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: node3
    expose:         #不会将端口暴露给容器外应用
      - "9003"
    ports:          #将端口暴露到宿主机中
      - "9202:9202"
      - "9302:9302"
    volumes:
      - ./node3/node3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      es-network:
        ipv4_address: 172.21.0.12
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5602:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://node1:9200
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - es-network
  filebeat:
    image: elastic/filebeat:7.10.1
    hostname: filebeat
    restart: always
    privileged: true
    command: /usr/share/filebeat/filebeat setup -e 
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./mocklog/logs:/usr/share/filebeat/data
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - es-network
  # logstash:
  #   hostname: logstash
  #   image: logstash:7.10.1
  #   command: logstash -f ./config/logstash.conf
  #   ports:
  #     - 5044:5044
  #   volumes:
  #     - ./logstash-conf:/usr/share/logstash/config
  #     - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  #   depends_on:
  #     - node1
  #     - node2
  #     - node3
  #     - kibana
  #   networks:
  #     - es-network
networks:
  es-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
