version: "2.1"
services: 
  logstash:
    hostname: logstash
    image: logstash:7.10.1
    container_name: logstash
    command: logstash -f ./config/filebeat.conf --config.reload.automatic
    ports:
      - 5044:5044
    volumes:
      - ./config:/usr/share/logstash/config
      - ./data:/usr/share/logstash/data
    networks:
      - elk_es-network
networks:
 elk_es-network:
  external: true