version: '3'
services:
  zk2:
    image: zookeeper:3.5
    container_name: zk2
    hostname: zk2
    networks:
      - ck-net

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    hostname: kafka
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  # 本机IP或直接填写kafka
      KAFKA_ZOOKEEPER_CONNECT: zk2:2181
      KAFKA_CREATE_TOPICS: "ck:3:1"  # topic名称:分区数量:副本数量
    networks:
      - ck-net
    depends_on:
      - zk2

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.4.2
    container_name: kafka-exporter
    hostname: kafka-exporter
    networks:
      - ck-net
    depends_on:
      - kafka


networks:
  ck-net:
    external: true
